server:
  port: 8087

spring:
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
  datasource:
    url: jdbc:h2:mem:currency_db
    driverClassName: org.h2.Driver
    username: sa
    password: password
#  jpa:
#    deferDatasourceInitialization: true